version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: liter-postgres
    restart: always
    environment:
      POSTGRES_DB: liter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "763"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
